// Auto-generated by LibreLane
module efpga_core(
`ifdef USE_POWER_PINS
  inout vssd1,
  inout vccd1,
`endif
  input[27:0] io_in,
  output[27:0] io_out,
  output[27:0] io_oeb,
  input clk,
  input resetn,
  input Rx,
  output ComActive,
  output ReceiveLED
);
endmodule
